import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../lib/sanity";
import { Post } from "../type";
interface Props {
	posts: [Post];
}

const Home = (props: Props) => {

	return (
		<div className="max-w-6xl mx-auto  ">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Banner />
		</div>
	);
};

export const getServerSideProps = async () => {
	const query = `*[_type == 'post']{ 
		_id, 
		title,
		description,
		mainImage,
		slug,
		author->{
			name,
			slug,
			image,
			bio
		}
	} `;

	const posts = await sanityClient.fetch(query);
	return {
		props: {
			posts,
		},
	};
};

export default Home;
