import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Header from "../components/Header";

const Home: NextPage = () => {
	return (
		<div className="max-w-6xl mx-auto  ">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Banner />
		</div>
	);
};

export default Home;
